routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes(['register' => false]);

Route::get('/', 'HomeController@index')->name('home');
Route::resource('projects', 'ProjectController');
Route::resource('sound_format', 'SoundFormatController');
Route::resource('settings', 'SettingController');

app/Project.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Project extends Model
{
    //
}

app/Http/Controllers/ProjectController.php
<?php

namespace App\Http\Controllers;

use App\Project;
use Illuminate\Http\Request;

class ProjectController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $projects = Project::all();
        return view('project.index')->with(compact('projects'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Project  $project
     * @return \Illuminate\Http\Response
     */
    public function show(Project $project)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Project  $project
     * @return \Illuminate\Http\Response
     */
    public function edit(Project $project)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Project  $project
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Project $project)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Project  $project
     * @return \Illuminate\Http\Response
     */
    public function destroy(Project $project)
    {
        //
    }
}

resources/views/project/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
	<div class="row">
		<div class="col">
			<div class="card bg-primary">
				<div class="card-header text-white">
					<span class="card-justify-middle float-left">Projekti</span> <a class="btn btn-secondary float-right" href="{{ route('projects.create') }}">Pievienot jaunu</a>
				</div>
				<div class="card-body bg-white">
					<table class="table">
						<thead>
							<tr>
								<th>id</th>
								<th>Nosaukums LV</th>
								<th>Nosaukums EN</th>
								<th>Nosaukums Oriģinālvalodā</th>
								<th>Sinopse LV</th>
								<th>Sinopse EN</th>
								<th>Projekta Veids</th>
								<th>Metrāža</th>
								<th>Garums (MIN)</th>
								<th>Īstenošanas laiks (NO)</th>
								<th>Īstenošanas laiks (LĪDZ)</th>
								<th></th>
							</tr>
							<tr>
								<td>Kaut kas</td>
							</tr>
						</thead>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection