routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes(['register' => false]);

Route::get('/', 'HomeController@index')->name('home');
Route::resource('projects', 'ProjectController');
Route::resource('sound_format', 'SoundFormatController');
Route::resource('settings', 'SettingController');

app/Sound_format.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Sound_format extends Model
{
    //
}

app/Http/Controllers/SoundFormatController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Sound_format;
use Session;

class SoundFormatController extends Controller
{
    public function index(Request $request)
    {
    	$sound_formats = Sound_format::all();
    	return view('sound_format.index')->with(compact('sound_formats'));
    }

    public function edit($id)
    {
    	$sound_format = Sound_format::findOrFail($id);
    	return view('sound_format.edit')->with(compact('sound_format'));
    }

    public function update(Request $request, $id)
    {
    	$sound_format = Sound_format::findOrFail($id);
    	$sound_format->title = $request->input('title');
    	$sound_format->timestamps = false;
    	if ($sound_format->save())
    	{
    		return redirect(route('sound_format.index'))->with(['status' => 'success', 'message' => 'Ieraksts veiksmīgi labots!']);
    	} else {
    		return redirect(route('sound_format.index'))->with(['status' => 'danger', 'message' => 'Notika kļūda!']);
    	}
    }

    public function create()
    {
    	return view('sound_format.create');
    }

    public function store(Request $request)
    {
    	$sound_format = new Sound_format();
    	$sound_format->title = $request->input('title');
    	$sound_format->timestamps = false;
    	if ($sound_format->save())
    	{
    		return redirect(route('sound_format.index'))->with(['status' => 'success', 'message' => 'Veiksmīgi izveidojis ierakstu!']);
    	} else {
    		return redirect(route('sound_format.index'))->with(['status' => 'danger', 'message' => 'Notika kļūda!']);
    	}
    }

    public function destroy($id)
    {
    	$sound_format = Sound_format::findOrFail($id);
    	if ($sound_format->delete())
    	{
    		return redirect(route('sound_format.index'))->with(['status' => 'success', 'message' => 'Veiksmīgi dzēsts ieraksts!']);
    	} else {
    		return redirect(route('sound_format.index'))->with(['status' => 'danger', 'message' => 'Notika kļūda!']);
    	}
    }
}

resources/views/sound_format/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
	<div class="row">
		<div class="col">
			<div class="card bg-primary">
				<div class="card-header text-white">
					<span>Pievienot jaunu</span>
				</div>
				<div class="card-body bg-white">
					<form method="post" action="{{ route('sound_format.store') }}">
						@csrf
						<div class="form-group">
							<input class="form-control" type="text" name="title" placeholder="Skaņas formāta nosaukums" autofocus="" required="">
						</div>
						<button class="btn btn-success" type="submit">Izveidot</button>
						<a href="{{ route('sound_format.index') }}" class="btn btn-primary">Atgriezties atpakaļ</a>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/sound_format/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
	<div class="row">
		<div class="col">
			<div class="card bg-primary">
				<div class="card-header text-white">
					<span>Labot ierakstu - {{ $sound_format['id'] }} ( {{ $sound_format['title'] }} )</span>
				</div>
				<div class="card-body bg-white">
					<form method="post" action="{{ route('sound_format.update', $sound_format['id']) }}">
						@csrf
						{{ method_field('PUT') }}
						<div class="form-group">
							<input class="form-control" type="text" name="title" placeholder="Skaņas formāta nosaukums" @if ($sound_format['title']) value="{{ $sound_format['title'] }}" @endif autofocus="" required="">
						</div>
						<button class="btn btn-success" type="submit">Labot</button>
						<a href="{{ route('sound_format.index') }}" class="btn btn-primary">Atgriezties atpakaļ</a>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/sound_format/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
	<div class="row">
		<div class="col">
			@if (session('status'))
		    	<div class="alert alert-{{ session('status') }}">
		    		{{ session('message') }}
		    	</div>
		    @endif
			<div class="card bg-primary">
				<div class="card-header text-white">
					<span class="card-justify-middle float-left">Skaņu formāti</span> <a class="btn btn-secondary float-right" href="{{ route('sound_format.create') }}">Pievienot jaunu</a>
				</div>
				<table class="table bg-white">
					<thead>
						<tr>
							<th>id</th>
							<th>Nosaukums</th>
							<th></th>
						</tr>
						@foreach ($sound_formats as $sound_format)
							<tr class="clickableRow" href="{{ route('sound_format.edit', $sound_format['id']) }}">
								<td>{{ $sound_format['id'] }}</td>
								<td>{{ $sound_format['title'] }}</td>
								<td class="delete">
									<form method="post" action="{{ route('sound_format.destroy', $sound_format['id']) }}">
										@csrf
										{{ method_field('DELETE') }}
										<button class="btn float-right">
											<svg class="bi bi-x" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
											  <path fill-rule="evenodd" d="M11.854 4.146a.5.5 0 010 .708l-7 7a.5.5 0 01-.708-.708l7-7a.5.5 0 01.708 0z" clip-rule="evenodd"/>
											  <path fill-rule="evenodd" d="M4.146 4.146a.5.5 0 000 .708l7 7a.5.5 0 00.708-.708l-7-7a.5.5 0 00-.708 0z" clip-rule="evenodd"/>
											</svg>
										</button>
									</form>
								</td>
							</tr>
						@endforeach
					</thead>
				</table>
			</div>
		</div>
	</div>
</div>
@endsection